// SPDX-License-Identifier: AGPL-3.0-or-later
// In-memory dataset for ZaloCRM standalone preview mode

const now = Date.now();
const isoAgo = (mins: number) => new Date(now - mins * 60_000).toISOString();
const isoFuture = (mins: number) => new Date(now + mins * 60_000).toISOString();

export const DEMO_USER = {
  id: 'u-owner-1',
  email: 'admin@hsholding.vn',
  phone: '0901234567',
  fullName: 'Nguyễn Tiến Lộc',
  role: 'owner',
  orgId: 'org-hs-1',
  org: {
    id: 'org-hs-1',
    name: 'HS Holding',
    timezone: '+07:00',
    slogan: 'Bền vững · Trường tồn',
  },
  orgName: 'HS Holding',
  orgTimezone: '+07:00',
  avatarUrl: null,
  passwordChangedAt: '2026-05-01T08:00:00.000Z',
  onboardingDismissedAt: '2026-05-01T09:00:00.000Z',
  grants: {},
  permissionGroup: { id: 'pg-owner', name: 'Chủ sở hữu (Toàn quyền)', isSystem: true },
  permissionGroupName: 'Chủ sở hữu (Toàn quyền)',
  isFullAccess: true,
  deptRole: 'leader',
  departmentId: 'dept-bds-1',
  canViewAll: true,
};

export const DEMO_USERS = [
  {
    id: 'u-owner-1',
    email: 'admin@hsholding.vn',
    phone: '0901234567',
    avatarUrl: null,
    fullName: 'Nguyễn Tiến Lộc',
    role: 'owner',
    permissionGroupId: 'pg-owner',
    permissionGroup: { id: 'pg-owner', name: 'Chủ sở hữu', isSystem: true },
    departmentMember: {
      departmentId: 'dept-bds-1',
      deptRole: 'leader',
      department: { id: 'dept-bds-1', name: 'Khối Kinh Doanh BĐS', path: '/dept-bds-1' },
    },
    internalContactMethod: 'crm_nick',
    internalContactPhone: '0901234567',
    internalContactZaloAccountId: 'za-1',
    internalContactNick: { id: 'za-1', displayName: 'Lộc Nguyễn — Giám Đốc Dự Án', avatarUrl: null, phone: '0901234567', zaloUid: 'zuid_loc_01', status: 'connected' },
    recipientStatus: 'ready',
    recipientError: null,
    maxPrivacyNicks: 3,
    passwordChangedAt: '2026-05-01T08:00:00.000Z',
    lastLoginAt: isoAgo(5),
    isActive: true,
  },
  {
    id: 'u-sale-1',
    email: 'minhanh@hsholding.vn',
    phone: '0908112233',
    avatarUrl: null,
    fullName: 'Trần Minh Anh',
    role: 'member',
    permissionGroupId: 'pg-senior-sale',
    permissionGroup: { id: 'pg-senior-sale', name: 'Sale Senior', isSystem: true },
    departmentMember: {
      departmentId: 'dept-bds-2',
      deptRole: 'leader',
      department: { id: 'dept-bds-2', name: 'Phòng Kinh Doanh 1 — Đông Sài Gòn', path: '/dept-bds-1/dept-bds-2' },
    },
    internalContactMethod: 'crm_nick',
    internalContactPhone: '0908112233',
    internalContactZaloAccountId: 'za-2',
    internalContactNick: { id: 'za-2', displayName: 'Minh Anh BĐS Vinhomes', avatarUrl: null, phone: '0908112233', zaloUid: 'zuid_ma_02', status: 'connected' },
    recipientStatus: 'ready',
    recipientError: null,
    maxPrivacyNicks: 1,
    passwordChangedAt: '2026-05-05T08:00:00.000Z',
    lastLoginAt: isoAgo(18),
    isActive: true,
  },
  {
    id: 'u-sale-2',
    email: 'hoangnam@hsholding.vn',
    phone: '0919445566',
    avatarUrl: null,
    fullName: 'Lê Hoàng Nam',
    role: 'member',
    permissionGroupId: 'pg-sale',
    permissionGroup: { id: 'pg-sale', name: 'Chuyên viên Kinh doanh', isSystem: true },
    departmentMember: {
      departmentId: 'dept-bds-2',
      deptRole: 'member',
      department: { id: 'dept-bds-2', name: 'Phòng Kinh Doanh 1 — Đông Sài Gòn', path: '/dept-bds-1/dept-bds-2' },
    },
    internalContactMethod: 'crm_nick',
    internalContactPhone: '0919445566',
    internalContactZaloAccountId: 'za-3',
    internalContactNick: { id: 'za-3', displayName: 'Hoàng Nam — Chuyên Viên Tư Vấn', avatarUrl: null, phone: '0919445566', zaloUid: 'zuid_hn_03', status: 'connected' },
    recipientStatus: 'ready',
    recipientError: null,
    maxPrivacyNicks: 1,
    passwordChangedAt: '2026-05-10T08:00:00.000Z',
    lastLoginAt: isoAgo(42),
    isActive: true,
  },
  {
    id: 'u-sale-3',
    email: 'thao.pham@hsholding.vn',
    phone: '0987654321',
    avatarUrl: null,
    fullName: 'Phạm Phương Thảo',
    role: 'member',
    permissionGroupId: 'pg-sale',
    permissionGroup: { id: 'pg-sale', name: 'Chuyên viên Kinh doanh', isSystem: true },
    departmentMember: {
      departmentId: 'dept-bds-3',
      deptRole: 'leader',
      department: { id: 'dept-bds-3', name: 'Phòng Kinh Doanh 2 — Khu Nam', path: '/dept-bds-1/dept-bds-3' },
    },
    internalContactMethod: 'personal_phone',
    internalContactPhone: '0987654321',
    internalContactZaloAccountId: null,
    internalContactNick: null,
    recipientStatus: 'ready',
    recipientError: null,
    maxPrivacyNicks: 1,
    passwordChangedAt: '2026-05-12T08:00:00.000Z',
    lastLoginAt: isoAgo(120),
    isActive: true,
  },
];

export const DEMO_ZALO_ACCOUNTS = [
  {
    id: 'za-1',
    zaloUid: 'zuid_loc_01',
    displayName: 'Lộc Nguyễn — Giám Đốc Dự Án',
    avatarUrl: null,
    phone: '0901234567',
    status: 'connected',
    liveStatus: 'connected',
    hasProxy: true,
    proxyUrl: 'http://***:***@103.82.24.11:8080',
    lastConnectedAt: isoAgo(120),
    disconnectedAt: null,
    disconnectReason: null,
    createdAt: '2026-01-15T08:00:00.000Z',
    ownerUserId: 'u-owner-1',
    owner: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
    ownerDepartment: { id: 'dept-bds-1', name: 'Khối Kinh Doanh BĐS', path: '/dept-bds-1' },
    ownerDeptRole: 'leader',
    isInternalContactFor: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc' },
    canManage: true,
    isOwnedByMe: true,
    privacyMode: 'sub',
    crew: [
      { accessId: 'acc-1', permission: 'admin', role: 'owner', user: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' } },
      { accessId: 'acc-2', permission: 'chat', role: 'editor', user: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' } },
    ],
    crewCount: 2,
    msgToday: 148,
    quota: 300,
    uptime7d: 99.4,
    lastActivityAt: isoAgo(3),
    healthAlert: false,
    metricsToday: {
      msgReceivedFromFriends: 82,
      msgReceivedFromStrangers: 19,
      msgReceivedTotal: 101,
      msgSentByUser: 112,
      msgSentByBot: 36,
      msgSentTotal: 148,
      msgSentToStrangers: 24,
      msgSentToFriends: 124,
      friendReqSent: 18,
      friendReqAccepted: 12,
      friendReqRejected: 1,
      friendReqByUser: 8,
      friendReqByBot: 10,
      phoneSearchTotal: 25,
      phoneSearchFoundZalo: 22,
      phoneSearchNoZalo: 3,
      phoneSearchByUser: 9,
      phoneSearchByBot: 16,
    },
  },
  {
    id: 'za-2',
    zaloUid: 'zuid_ma_02',
    displayName: 'Minh Anh BĐS Vinhomes',
    avatarUrl: null,
    phone: '0908112233',
    status: 'connected',
    liveStatus: 'connected',
    hasProxy: true,
    proxyUrl: 'http://***:***@103.82.24.12:8080',
    lastConnectedAt: isoAgo(340),
    disconnectedAt: null,
    disconnectReason: null,
    createdAt: '2026-02-01T08:00:00.000Z',
    ownerUserId: 'u-sale-1',
    owner: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' },
    ownerDepartment: { id: 'dept-bds-2', name: 'Phòng Kinh Doanh 1 — Đông Sài Gòn', path: '/dept-bds-1/dept-bds-2' },
    ownerDeptRole: 'leader',
    isInternalContactFor: { id: 'u-sale-1', fullName: 'Trần Minh Anh' },
    canManage: true,
    isOwnedByMe: false,
    privacyMode: 'sub',
    crew: [
      { accessId: 'acc-3', permission: 'admin', role: 'owner', user: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' } },
    ],
    crewCount: 1,
    msgToday: 215,
    quota: 300,
    uptime7d: 98.2,
    lastActivityAt: isoAgo(7),
    healthAlert: false,
    metricsToday: {
      msgReceivedFromFriends: 110,
      msgReceivedFromStrangers: 32,
      msgReceivedTotal: 142,
      msgSentByUser: 160,
      msgSentByBot: 55,
      msgSentTotal: 215,
      msgSentToStrangers: 41,
      msgSentToFriends: 174,
      friendReqSent: 24,
      friendReqAccepted: 15,
      friendReqRejected: 2,
      friendReqByUser: 10,
      friendReqByBot: 14,
      phoneSearchTotal: 28,
      phoneSearchFoundZalo: 25,
      phoneSearchNoZalo: 3,
      phoneSearchByUser: 12,
      phoneSearchByBot: 16,
    },
  },
  {
    id: 'za-3',
    zaloUid: 'zuid_hn_03',
    displayName: 'Hoàng Nam — Chuyên Viên Tư Vấn',
    avatarUrl: null,
    phone: '0919445566',
    status: 'connected',
    liveStatus: 'connected',
    hasProxy: true,
    proxyUrl: 'http://***:***@103.82.24.13:8080',
    lastConnectedAt: isoAgo(600),
    disconnectedAt: null,
    disconnectReason: null,
    createdAt: '2026-02-20T08:00:00.000Z',
    ownerUserId: 'u-sale-2',
    owner: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam', email: 'hoangnam@hsholding.vn' },
    ownerDepartment: { id: 'dept-bds-2', name: 'Phòng Kinh Doanh 1 — Đông Sài Gòn', path: '/dept-bds-1/dept-bds-2' },
    ownerDeptRole: 'member',
    isInternalContactFor: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam' },
    canManage: true,
    isOwnedByMe: false,
    privacyMode: 'sub',
    crew: [
      { accessId: 'acc-4', permission: 'admin', role: 'owner', user: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam', email: 'hoangnam@hsholding.vn' } },
    ],
    crewCount: 1,
    msgToday: 94,
    quota: 300,
    uptime7d: 96.8,
    lastActivityAt: isoAgo(19),
    healthAlert: false,
    metricsToday: {
      msgReceivedFromFriends: 48,
      msgReceivedFromStrangers: 14,
      msgReceivedTotal: 62,
      msgSentByUser: 74,
      msgSentByBot: 20,
      msgSentTotal: 94,
      msgSentToStrangers: 18,
      msgSentToFriends: 76,
      friendReqSent: 12,
      friendReqAccepted: 7,
      friendReqRejected: 0,
      friendReqByUser: 6,
      friendReqByBot: 6,
      phoneSearchTotal: 15,
      phoneSearchFoundZalo: 13,
      phoneSearchNoZalo: 2,
      phoneSearchByUser: 7,
      phoneSearchByBot: 8,
    },
  },
  {
    id: 'za-4',
    zaloUid: 'zuid_cskh_04',
    displayName: 'CSKH HS Holding — Hotline Dự Án',
    avatarUrl: null,
    phone: '0938998877',
    status: 'disconnected',
    liveStatus: 'disconnected',
    hasProxy: false,
    proxyUrl: null,
    lastConnectedAt: isoAgo(1440),
    disconnectedAt: isoAgo(180),
    disconnectReason: 'passive',
    createdAt: '2026-03-05T08:00:00.000Z',
    ownerUserId: 'u-sale-3',
    owner: { id: 'u-sale-3', fullName: 'Phạm Phương Thảo', email: 'thao.pham@hsholding.vn' },
    ownerDepartment: { id: 'dept-bds-3', name: 'Phòng Kinh Doanh 2 — Khu Nam', path: '/dept-bds-1/dept-bds-3' },
    ownerDeptRole: 'leader',
    isInternalContactFor: null,
    canManage: true,
    isOwnedByMe: false,
    privacyMode: 'sub',
    crew: [
      { accessId: 'acc-5', permission: 'admin', role: 'owner', user: { id: 'u-sale-3', fullName: 'Phạm Phương Thảo', email: 'thao.pham@hsholding.vn' } },
    ],
    crewCount: 1,
    msgToday: 12,
    quota: 300,
    uptime7d: 78.5,
    lastActivityAt: isoAgo(195),
    healthAlert: true,
    metricsToday: {
      msgReceivedFromFriends: 9,
      msgReceivedFromStrangers: 2,
      msgReceivedTotal: 11,
      msgSentByUser: 12,
      msgSentByBot: 0,
      msgSentTotal: 12,
      msgSentToStrangers: 2,
      msgSentToFriends: 10,
      friendReqSent: 2,
      friendReqAccepted: 1,
      friendReqRejected: 0,
      friendReqByUser: 2,
      friendReqByBot: 0,
      phoneSearchTotal: 4,
      phoneSearchFoundZalo: 3,
      phoneSearchNoZalo: 1,
      phoneSearchByUser: 4,
      phoneSearchByBot: 0,
    },
  },
];

export const DEMO_STATUSES = [
  { id: 'st-new', name: 'Mới tiếp cận', color: '#3B82F6', order: 1, isTerminal: false },
  { id: 'st-contacted', name: 'Đang tư vấn', color: '#0EA5E9', order: 2, isTerminal: false },
  { id: 'st-interested', name: 'Quan tâm sâu', color: '#F59E0B', order: 3, isTerminal: false },
  { id: 'st-sitevisit', name: 'Đã hẹn xem sa bàn', color: '#8B5CF6', order: 4, isTerminal: false },
  { id: 'st-converted', name: 'Đã giữ chỗ / Chốt', color: '#10B981', order: 5, isTerminal: true },
  { id: 'st-lost', name: 'Tạm ngưng', color: '#64748B', order: 6, isTerminal: true },
];

export const DEMO_TAGS = [
  { id: 'tg-1', name: 'VIP Đầu tư', slug: 'vip-dau-tu', color: '#EF4444', emoji: '💎', scope: 'crm', source: 'manual', priority: 1, usageCount: 18, archivedAt: null },
  { id: 'tg-2', name: 'Tiềm năng cao', slug: 'tiem-nang', color: '#F59E0B', emoji: '🔥', scope: 'crm', source: 'manual', priority: 2, usageCount: 34, archivedAt: null },
  { id: 'tg-3', name: 'The Global City', slug: 'the-global-city', color: '#0EA5E9', emoji: '🏙', scope: 'crm', source: 'manual', priority: 3, usageCount: 27, archivedAt: null },
  { id: 'tg-4', name: 'Vinhomes Grand Park', slug: 'vinhomes-grand-park', color: '#10B981', emoji: '🏡', scope: 'crm', source: 'manual', priority: 4, usageCount: 41, archivedAt: null },
  { id: 'tg-5', name: 'Eaton Park Mai Chí Thọ', slug: 'eaton-park', color: '#8B5CF6', emoji: '✨', scope: 'crm', source: 'manual', priority: 5, usageCount: 19, archivedAt: null },
  { id: 'tg-6', name: 'Khách nét tuần này', slug: 'khach-net-tuan-nay', color: '#EC4899', emoji: '⭐', scope: 'friend', source: 'zalo_real', priority: 1, usageCount: 22, archivedAt: null, zaloAccount: { id: 'za-1', displayName: 'Lộc Nguyễn — Giám Đốc Dự Án' } },
  { id: 'tg-7', name: 'Chờ gửi bảng tính dòng tiền', slug: 'cho-gui-bang-tinh', color: '#14B8A6', emoji: '📊', scope: 'friend', source: 'manual', priority: 2, usageCount: 15, archivedAt: null },
];

export const DEMO_CONTACTS = [
  {
    id: 'ct-1',
    fullName: 'Đặng Quốc Khánh',
    crmName: 'Anh Khánh — Nhà đầu tư Quận 2',
    phone: '0903888999',
    email: 'khanh.dang@vietcapital.vn',
    avatarUrl: null,
    source: 'FB',
    sourceDate: '2026-04-12T08:30:00.000Z',
    status: 'interested',
    statusId: 'st-interested',
    statusRef: DEMO_STATUSES[2],
    displayStatus: DEMO_STATUSES[2],
    zaloUid: 'zuid_kh_101',
    zaloGlobalId: 'gid_kh_101',
    zaloUsername: 'khanh_dq88',
    aggregateZaloGlobalId: 'gid_kh_101',
    aggregateZaloUsername: 'khanh_dq88',
    distinctGlobalIdCount: 1,
    distinctUsernameCount: 1,
    hasZalo: true,
    displayHasZalo: true,
    leadScore: 86,
    displayLeadScore: 86,
    priorityScore: 84,
    engagementPattern: 'hot',
    engagementScore: 88,
    engagementTrend: 14,
    tags: ['vip-dau-tu', 'the-global-city', 'tiem-nang'],
    notes: 'Quan tâm shophouse SOHO và căn 3PN view sông tại Eaton Park. Tài chính sẵn sàng 15–25 tỷ.',
    assignedUserId: 'u-owner-1',
    assignedUser: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
    viewerRole: 'admin',
    contactAccess: [
      { role: 'primary', source: 'manual', createdAt: '2026-04-12T08:30:00.000Z', user: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' } },
      { role: 'collaborator', source: 'chat', createdAt: '2026-04-14T10:00:00.000Z', user: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' } },
    ],
    nicksByKind: { friend: 2 },
    childrenCount: 2,
    gender: 'male',
    birthYear: 1982,
    province: 'TP. Hồ Chí Minh',
    district: 'TP. Thủ Đức',
    incomeRange: 'gt_100m',
    lastInboundAt: isoAgo(4),
    lastInboundPreview: 'Em gửi giúp anh mặt bằng tầng 18 căn góc 3PN và lịch thanh toán chiết khấu 8% nhé.',
    lastInboundType: 'text',
    lastOutboundAt: isoAgo(12),
    lastOutboundPreview: 'Dạ anh Khánh, hiện giỏ hàng độc quyền bên em vừa mở 2 căn góc view trực diện sông Sài Gòn ạ.',
    lastOutboundType: 'text',
    lastInteractionAt: isoAgo(4),
    lastActivity: isoAgo(4),
    totalInbound: 38,
    totalOutbound: 42,
    totalAppointments: 2,
    nextAppointment: isoFuture(180),
    sequenceAttachCount: 1,
    sequenceActiveCount: 1,
    friendInviteSentCount: 1,
    mergedInto: null,
  },
  {
    id: 'ct-2',
    fullName: 'Vũ Thị Bích Ngọc',
    crmName: 'Chị Ngọc — Chủ chuỗi Spa Thảo Điền',
    phone: '0918223344',
    email: 'bichngoc.spa@gmail.com',
    avatarUrl: null,
    source: 'GT',
    sourceDate: '2026-04-18T14:00:00.000Z',
    status: 'sitevisit',
    statusId: 'st-sitevisit',
    statusRef: DEMO_STATUSES[3],
    displayStatus: DEMO_STATUSES[3],
    zaloUid: 'zuid_kh_102',
    zaloGlobalId: 'gid_kh_102',
    zaloUsername: 'ngocvu_td',
    aggregateZaloGlobalId: 'gid_kh_102',
    aggregateZaloUsername: 'ngocvu_td',
    distinctGlobalIdCount: 1,
    distinctUsernameCount: 1,
    hasZalo: true,
    displayHasZalo: true,
    leadScore: 92,
    displayLeadScore: 92,
    priorityScore: 90,
    engagementPattern: 'champion',
    engagementScore: 91,
    engagementTrend: 18,
    tags: ['vip-dau-tu', 'eaton-park'],
    notes: 'Khách được anh Minh giới thiệu. Muốn xem thực tế nhà mẫu vào chiều nay lúc 15:30.',
    assignedUserId: 'u-sale-1',
    assignedUser: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' },
    viewerRole: 'admin',
    contactAccess: [
      { role: 'primary', source: 'manual', createdAt: '2026-04-18T14:00:00.000Z', user: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' } },
    ],
    nicksByKind: { friend: 1 },
    childrenCount: 1,
    gender: 'female',
    birthYear: 1987,
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 1',
    incomeRange: 'gt_100m',
    lastInboundAt: isoAgo(9),
    lastInboundPreview: 'Chiều nay 3h30 chị ghé văn phòng bán hàng Mai Chí Thọ, em đăng ký sảnh đón giúp chị nha.',
    lastInboundType: 'text',
    lastOutboundAt: isoAgo(15),
    lastOutboundPreview: 'Dạ vâng chị Ngọc, em đã chuẩn bị sẵn sa bàn và bảng tính dòng tiền thuê cho chị rồi ạ!',
    lastOutboundType: 'text',
    lastInteractionAt: isoAgo(9),
    lastActivity: isoAgo(9),
    totalInbound: 54,
    totalOutbound: 59,
    totalAppointments: 3,
    nextAppointment: isoFuture(120),
    sequenceAttachCount: 2,
    sequenceActiveCount: 1,
    friendInviteSentCount: 1,
    mergedInto: null,
  },
  {
    id: 'ct-3',
    fullName: 'Trịnh Đình Quang',
    crmName: 'Anh Quang — Kỹ sư CNTT',
    phone: '0977556677',
    email: 'quang.trinh@fpt.com.vn',
    avatarUrl: null,
    source: 'TT',
    sourceDate: '2026-04-25T09:15:00.000Z',
    status: 'contacted',
    statusId: 'st-contacted',
    statusRef: DEMO_STATUSES[1],
    displayStatus: DEMO_STATUSES[1],
    zaloUid: 'zuid_kh_103',
    zaloGlobalId: 'gid_kh_103',
    zaloUsername: 'quangtd_dev',
    aggregateZaloGlobalId: 'gid_kh_103',
    aggregateZaloUsername: 'quangtd_dev',
    distinctGlobalIdCount: 1,
    distinctUsernameCount: 1,
    hasZalo: true,
    displayHasZalo: true,
    leadScore: 68,
    displayLeadScore: 68,
    priorityScore: 66,
    engagementPattern: 'stable',
    engagementScore: 70,
    engagementTrend: 5,
    tags: ['vinhomes-grand-park', 'tiem-nang'],
    notes: 'Tìm căn 2PN+1 phân khu Beverly Solari vay ngân hàng 70%, ân hạn gốc 24 tháng.',
    assignedUserId: 'u-sale-2',
    assignedUser: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam', email: 'hoangnam@hsholding.vn' },
    viewerRole: 'admin',
    contactAccess: [
      { role: 'primary', source: 'lead_pool', createdAt: '2026-04-25T09:15:00.000Z', user: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam', email: 'hoangnam@hsholding.vn' } },
    ],
    nicksByKind: { friend: 1 },
    childrenCount: 1,
    gender: 'male',
    birthYear: 1993,
    province: 'TP. Hồ Chí Minh',
    district: 'TP. Thủ Đức',
    incomeRange: '50_100m',
    lastInboundAt: isoAgo(27),
    lastInboundPreview: 'Gói vay Vietcombank hiện tại lãi suất sau ưu đãi tính biên độ thế nào bạn ơi?',
    lastInboundType: 'text',
    lastOutboundAt: isoAgo(45),
    lastOutboundPreview: 'Em gửi anh bảng minh họa gốc lãi chi tiết 24 tháng đầu 0% của phân khu The Beverly ạ.',
    lastOutboundType: 'text',
    lastInteractionAt: isoAgo(27),
    lastActivity: isoAgo(27),
    totalInbound: 19,
    totalOutbound: 23,
    totalAppointments: 1,
    nextAppointment: isoFuture(1440),
    sequenceAttachCount: 1,
    sequenceActiveCount: 1,
    friendInviteSentCount: 1,
    mergedInto: null,
  },
  {
    id: 'ct-4',
    fullName: 'Lương Mỹ Linh',
    crmName: 'Chị Mỹ Linh — Việt kiều Úc',
    phone: '0933445588',
    email: 'mylinh.luong@sydneyprop.au',
    avatarUrl: null,
    source: 'FB',
    sourceDate: '2026-04-02T11:20:00.000Z',
    status: 'converted',
    statusId: 'st-converted',
    statusRef: DEMO_STATUSES[4],
    displayStatus: DEMO_STATUSES[4],
    zaloUid: 'zuid_kh_104',
    zaloGlobalId: 'gid_kh_104',
    zaloUsername: 'mylinh_au',
    aggregateZaloGlobalId: 'gid_kh_104',
    aggregateZaloUsername: 'mylinh_au',
    distinctGlobalIdCount: 1,
    distinctUsernameCount: 1,
    hasZalo: true,
    displayHasZalo: true,
    leadScore: 95,
    displayLeadScore: 95,
    priorityScore: 92,
    engagementPattern: 'champion',
    engagementScore: 94,
    engagementTrend: 12,
    tags: ['vip-dau-tu', 'the-global-city'],
    notes: 'Đã vào cọc 200 triệu căn Penthouse Tòa A2. Đang hoàn tất thủ tục ủy quyền ký HĐMB.',
    assignedUserId: 'u-owner-1',
    assignedUser: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
    viewerRole: 'admin',
    contactAccess: [
      { role: 'primary', source: 'manual', createdAt: '2026-04-02T11:20:00.000Z', user: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' } },
    ],
    nicksByKind: { friend: 1 },
    childrenCount: 1,
    gender: 'female',
    birthYear: 1979,
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 7',
    incomeRange: 'gt_100m',
    lastInboundAt: isoAgo(95),
    lastInboundPreview: 'Chị đã nhận được xác nhận chuyển khoản giữ chỗ từ chủ đầu tư rồi, cảm ơn Lộc nhé!',
    lastInboundType: 'text',
    lastOutboundAt: isoAgo(80),
    lastOutboundPreview: 'Dạ em cảm ơn chị Linh tin tưởng đồng hành cùng HS Holding ạ! Hồ sơ HĐMB bên pháp lý đang soạn sẵn cho chị.',
    lastOutboundType: 'text',
    lastInteractionAt: isoAgo(80),
    lastActivity: isoAgo(80),
    totalInbound: 71,
    totalOutbound: 76,
    totalAppointments: 4,
    nextAppointment: null,
    sequenceAttachCount: 1,
    sequenceActiveCount: 0,
    friendInviteSentCount: 1,
    mergedInto: null,
  },
  {
    id: 'ct-5',
    fullName: 'Phan Thanh Tùng',
    crmName: 'Anh Tùng — Doanh nghiệp Logistics',
    phone: '0944667788',
    email: 'tung.phan@transvina.vn',
    avatarUrl: null,
    source: 'CN',
    sourceDate: '2026-04-10T15:00:00.000Z',
    status: 'interested',
    statusId: 'st-interested',
    statusRef: DEMO_STATUSES[2],
    displayStatus: DEMO_STATUSES[2],
    zaloUid: 'zuid_kh_105',
    zaloGlobalId: 'gid_kh_105',
    zaloUsername: 'tungphan_log',
    aggregateZaloGlobalId: 'gid_kh_105',
    aggregateZaloUsername: 'tungphan_log',
    distinctGlobalIdCount: 1,
    distinctUsernameCount: 1,
    hasZalo: true,
    displayHasZalo: true,
    leadScore: 74,
    displayLeadScore: 74,
    priorityScore: 71,
    engagementPattern: 'cooling',
    engagementScore: 58,
    engagementTrend: -8,
    tags: ['vinhomes-grand-park'],
    notes: 'Đang cân nhắc giữa dinh thự The Rivus và biệt thự đơn lập Manhattan Glory.',
    assignedUserId: 'u-sale-3',
    assignedUser: { id: 'u-sale-3', fullName: 'Phạm Phương Thảo', email: 'thao.pham@hsholding.vn' },
    viewerRole: 'admin',
    contactAccess: [
      { role: 'primary', source: 'manual', createdAt: '2026-04-10T15:00:00.000Z', user: { id: 'u-sale-3', fullName: 'Phạm Phương Thảo', email: 'thao.pham@hsholding.vn' } },
    ],
    nicksByKind: { pending_friend: 1 },
    childrenCount: 1,
    gender: 'male',
    birthYear: 1976,
    province: 'Bình Dương',
    district: 'TP. Thuận An',
    incomeRange: 'gt_100m',
    lastInboundAt: isoAgo(4320),
    lastInboundPreview: 'Tuần tới anh đi công tác về sẽ báo lại lịch qua xem thực tế khu biệt thự bến du thuyền.',
    lastInboundType: 'text',
    lastOutboundAt: isoAgo(2880),
    lastOutboundPreview: 'Dạ anh Tùng, em gửi anh video flycam tiến độ bến du thuyền tháng này để anh tiện xem trước ạ.',
    lastOutboundType: 'text',
    lastInteractionAt: isoAgo(2880),
    lastActivity: isoAgo(2880),
    totalInbound: 14,
    totalOutbound: 18,
    totalAppointments: 1,
    nextAppointment: null,
    sequenceAttachCount: 2,
    sequenceActiveCount: 1,
    friendInviteSentCount: 2,
    mergedInto: null,
  },
];

export const DEMO_CONVERSATIONS = [
  {
    id: 'conv-1',
    threadType: 'user' as const,
    contact: DEMO_CONTACTS[0],
    zaloAccount: { id: 'za-1', displayName: 'Lộc Nguyễn — Giám Đốc Dự Án', avatarUrl: null, privacyMode: 'sub' as const, ownerUserId: 'u-owner-1', archivedAt: null },
    externalThreadId: 'zuid_kh_101',
    friendship: {
      id: 'fr-1',
      relationshipKind: 'friend',
      friendshipStatus: 'accepted',
      hasConversation: true,
      becameFriendAt: '2026-04-12T09:00:00.000Z',
      firstMessageAt: '2026-04-12T08:35:00.000Z',
      updatedAt: isoAgo(4),
      totalInbound: 38,
      totalOutbound: 42,
      leadScore: 86,
      statusRef: DEMO_STATUSES[2],
      zaloLabels: [{ id: 'zl-1', name: 'VIP Đầu tư', color: '#EF4444' }],
      crmTagsPerNick: ['vip-dau-tu', 'the-global-city', 'khach-net-tuan-nay'],
      autoTags: ['active', 'ready', 'has-appointment'],
      aliasInNick: 'A Khánh Đầu Tư Q2',
      zaloDisplayName: 'Đặng Quốc Khánh',
      zaloAvatarUrl: null,
    },
    lastMessageAt: isoAgo(4),
    unreadCount: 2,
    isReplied: false,
    isPinned: true,
    messages: [
      {
        id: 'm-103',
        content: 'Em gửi giúp anh mặt bằng tầng 18 căn góc 3PN và lịch thanh toán chiết khấu 8% nhé.',
        contentType: 'text',
        senderType: 'contact',
        sentAt: isoAgo(4),
        isDeleted: false,
      },
    ],
  },
  {
    id: 'conv-2',
    threadType: 'user' as const,
    contact: DEMO_CONTACTS[1],
    zaloAccount: { id: 'za-2', displayName: 'Minh Anh BĐS Vinhomes', avatarUrl: null, privacyMode: 'sub' as const, ownerUserId: 'u-sale-1', archivedAt: null },
    externalThreadId: 'zuid_kh_102',
    friendship: {
      id: 'fr-2',
      relationshipKind: 'friend',
      friendshipStatus: 'accepted',
      hasConversation: true,
      becameFriendAt: '2026-04-18T14:10:00.000Z',
      firstMessageAt: '2026-04-18T14:05:00.000Z',
      updatedAt: isoAgo(9),
      totalInbound: 54,
      totalOutbound: 59,
      leadScore: 92,
      statusRef: DEMO_STATUSES[3],
      zaloLabels: [{ id: 'zl-2', name: 'Hẹn xem nhà mẫu', color: '#8B5CF6' }],
      crmTagsPerNick: ['vip-dau-tu', 'eaton-park'],
      autoTags: ['active', 'ready', 'has-appointment'],
      aliasInNick: 'Chị Ngọc Spa Thảo Điền',
      zaloDisplayName: 'Vũ Thị Bích Ngọc',
      zaloAvatarUrl: null,
    },
    lastMessageAt: isoAgo(9),
    unreadCount: 1,
    isReplied: false,
    isPinned: true,
    messages: [
      {
        id: 'm-203',
        content: 'Chiều nay 3h30 chị ghé văn phòng bán hàng Mai Chí Thọ, em đăng ký sảnh đón giúp chị nha.',
        contentType: 'text',
        senderType: 'contact',
        sentAt: isoAgo(9),
        isDeleted: false,
      },
    ],
  },
  {
    id: 'conv-3',
    threadType: 'user' as const,
    contact: DEMO_CONTACTS[2],
    zaloAccount: { id: 'za-3', displayName: 'Hoàng Nam — Chuyên Viên Tư Vấn', avatarUrl: null, privacyMode: 'sub' as const, ownerUserId: 'u-sale-2', archivedAt: null },
    externalThreadId: 'zuid_kh_103',
    friendship: {
      id: 'fr-3',
      relationshipKind: 'friend',
      friendshipStatus: 'accepted',
      hasConversation: true,
      becameFriendAt: '2026-04-25T10:00:00.000Z',
      firstMessageAt: '2026-04-25T09:20:00.000Z',
      updatedAt: isoAgo(27),
      totalInbound: 19,
      totalOutbound: 23,
      leadScore: 68,
      statusRef: DEMO_STATUSES[1],
      zaloLabels: [],
      crmTagsPerNick: ['vinhomes-grand-park', 'cho-gui-bang-tinh'],
      autoTags: ['active'],
      aliasInNick: 'Anh Quang FPT (2PN+)',
      zaloDisplayName: 'Trịnh Đình Quang',
      zaloAvatarUrl: null,
    },
    lastMessageAt: isoAgo(27),
    unreadCount: 1,
    isReplied: false,
    isPinned: false,
    messages: [
      {
        id: 'm-302',
        content: 'Gói vay Vietcombank hiện tại lãi suất sau ưu đãi tính biên độ thế nào bạn ơi?',
        contentType: 'text',
        senderType: 'contact',
        sentAt: isoAgo(27),
        isDeleted: false,
      },
    ],
  },
  {
    id: 'conv-4',
    threadType: 'user' as const,
    contact: DEMO_CONTACTS[3],
    zaloAccount: { id: 'za-1', displayName: 'Lộc Nguyễn — Giám Đốc Dự Án', avatarUrl: null, privacyMode: 'sub' as const, ownerUserId: 'u-owner-1', archivedAt: null },
    externalThreadId: 'zuid_kh_104',
    friendship: {
      id: 'fr-4',
      relationshipKind: 'friend',
      friendshipStatus: 'accepted',
      hasConversation: true,
      becameFriendAt: '2026-04-02T11:30:00.000Z',
      firstMessageAt: '2026-04-02T11:25:00.000Z',
      updatedAt: isoAgo(80),
      totalInbound: 71,
      totalOutbound: 76,
      leadScore: 95,
      statusRef: DEMO_STATUSES[4],
      zaloLabels: [{ id: 'zl-1', name: 'Đã giữ chỗ', color: '#10B981' }],
      crmTagsPerNick: ['vip-dau-tu', 'the-global-city'],
      autoTags: ['active'],
      aliasInNick: 'Chị Mỹ Linh (Đã cọc A2)',
      zaloDisplayName: 'Lương Mỹ Linh',
      zaloAvatarUrl: null,
    },
    lastMessageAt: isoAgo(80),
    unreadCount: 0,
    isReplied: true,
    isPinned: false,
    messages: [
      {
        id: 'm-402',
        content: 'Dạ em cảm ơn chị Linh tin tưởng đồng hành cùng HS Holding ạ! Hồ sơ HĐMB bên pháp lý đang soạn sẵn cho chị.',
        contentType: 'text',
        senderType: 'self',
        sentAt: isoAgo(80),
        isDeleted: false,
      },
    ],
  },
  {
    id: 'conv-5',
    threadType: 'group' as const,
    contact: null,
    groupName: 'Giỏ Hàng Độc Quyền Eaton Park & The Global City',
    groupAvatarUrl: null,
    groupMembersCount: 146,
    zaloAccount: { id: 'za-1', displayName: 'Lộc Nguyễn — Giám Đốc Dự Án', avatarUrl: null, privacyMode: 'sub' as const, ownerUserId: 'u-owner-1', archivedAt: null },
    externalThreadId: 'grp_bds_01',
    friendship: null,
    lastMessageAt: isoAgo(15),
    unreadCount: 0,
    isReplied: true,
    isPinned: false,
    messages: [
      {
        id: 'm-501',
        content: 'Cập nhật bảng hàng mới nhất lúc 14:00: Căn A2-18.06 đã lock thành công cho khách VIP của PKD1!',
        contentType: 'text',
        senderType: 'self',
        sentAt: isoAgo(15),
        isDeleted: false,
      },
    ],
  },
];

export const DEMO_MESSAGES_BY_CONV: Record<string, any[]> = {
  'conv-1': [
    {
      id: 'm-101',
      content: 'Chào Lộc, anh đang xem thông tin dự án Eaton Park bên Mai Chí Thọ, bên em có rổ hàng ngoại giao tầng trung không?',
      contentType: 'text',
      senderType: 'contact',
      senderName: 'Đặng Quốc Khánh',
      senderUid: 'zuid_kh_101',
      sentAt: isoAgo(35),
      isDeleted: false,
      zaloMsgId: 'zmsg_101',
      zaloMsgIdNum: '100001',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
    {
      id: 'm-102',
      content: 'Dạ anh Khánh, hiện giỏ hàng độc quyền bên em vừa mở 2 căn góc view trực diện sông Sài Gòn tầng 16 và 18 ạ. Để em gửi anh bảng tính chiết khấu thanh toán nhanh nhé!',
      contentType: 'text',
      senderType: 'self',
      senderName: 'Nguyễn Tiến Lộc',
      sentAt: isoAgo(12),
      isDeleted: false,
      zaloMsgId: 'zmsg_102',
      zaloMsgIdNum: '100002',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      deliveredAt: isoAgo(11),
      seenAt: isoAgo(10),
      repliedByUserId: 'u-owner-1',
      repliedBy: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
      sentVia: 'user',
      reactions: [{ emoji: '❤️', reactorId: 'zuid_kh_101', reactorName: 'Đặng Quốc Khánh', reactorSource: 'zalo' }],
    },
    {
      id: 'm-103',
      content: 'Em gửi giúp anh mặt bằng tầng 18 căn góc 3PN và lịch thanh toán chiết khấu 8% nhé.',
      contentType: 'text',
      senderType: 'contact',
      senderName: 'Đặng Quốc Khánh',
      senderUid: 'zuid_kh_101',
      sentAt: isoAgo(4),
      isDeleted: false,
      zaloMsgId: 'zmsg_103',
      zaloMsgIdNum: '100003',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
  ],
  'conv-2': [
    {
      id: 'm-201',
      content: 'Minh Anh ơi, chiều nay chị đi cùng ông xã qua xem sa bàn dự án được không em?',
      contentType: 'text',
      senderType: 'contact',
      senderName: 'Vũ Thị Bích Ngọc',
      senderUid: 'zuid_kh_102',
      sentAt: isoAgo(25),
      isDeleted: false,
      zaloMsgId: 'zmsg_201',
      zaloMsgIdNum: '200001',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
    {
      id: 'm-202',
      content: 'Dạ vâng chị Ngọc, em đã chuẩn bị sẵn sa bàn và bảng tính dòng tiền thuê cho chị rồi ạ!',
      contentType: 'text',
      senderType: 'self',
      senderName: 'Trần Minh Anh',
      sentAt: isoAgo(15),
      isDeleted: false,
      zaloMsgId: 'zmsg_202',
      zaloMsgIdNum: '200002',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      deliveredAt: isoAgo(14),
      seenAt: isoAgo(13),
      repliedByUserId: 'u-sale-1',
      repliedBy: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' },
      sentVia: 'user',
      reactions: [{ emoji: '👍', reactorId: 'zuid_kh_102', reactorName: 'Vũ Thị Bích Ngọc', reactorSource: 'zalo' }],
    },
    {
      id: 'm-203',
      content: 'Chiều nay 3h30 chị ghé văn phòng bán hàng Mai Chí Thọ, em đăng ký sảnh đón giúp chị nha.',
      contentType: 'text',
      senderType: 'contact',
      senderName: 'Vũ Thị Bích Ngọc',
      senderUid: 'zuid_kh_102',
      sentAt: isoAgo(9),
      isDeleted: false,
      zaloMsgId: 'zmsg_203',
      zaloMsgIdNum: '200003',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
  ],
  'conv-3': [
    {
      id: 'm-301',
      content: 'Em gửi anh bảng minh họa gốc lãi chi tiết 24 tháng đầu 0% của phân khu The Beverly ạ.',
      contentType: 'text',
      senderType: 'self',
      senderName: 'Lê Hoàng Nam',
      sentAt: isoAgo(45),
      isDeleted: false,
      zaloMsgId: 'zmsg_301',
      zaloMsgIdNum: '300001',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      deliveredAt: isoAgo(44),
      seenAt: isoAgo(40),
      repliedByUserId: 'u-sale-2',
      repliedBy: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam', email: 'hoangnam@hsholding.vn' },
      sentVia: 'user',
      reactions: [],
    },
    {
      id: 'm-302',
      content: 'Gói vay Vietcombank hiện tại lãi suất sau ưu đãi tính biên độ thế nào bạn ơi?',
      contentType: 'text',
      senderType: 'contact',
      senderName: 'Trịnh Đình Quang',
      senderUid: 'zuid_kh_103',
      sentAt: isoAgo(27),
      isDeleted: false,
      zaloMsgId: 'zmsg_302',
      zaloMsgIdNum: '300002',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
  ],
  'conv-4': [
    {
      id: 'm-401',
      content: 'Chị đã nhận được xác nhận chuyển khoản giữ chỗ từ chủ đầu tư rồi, cảm ơn Lộc nhé!',
      contentType: 'text',
      senderType: 'contact',
      senderName: 'Lương Mỹ Linh',
      senderUid: 'zuid_kh_104',
      sentAt: isoAgo(95),
      isDeleted: false,
      zaloMsgId: 'zmsg_401',
      zaloMsgIdNum: '400001',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
    {
      id: 'm-402',
      content: 'Dạ em cảm ơn chị Linh tin tưởng đồng hành cùng HS Holding ạ! Hồ sơ HĐMB bên pháp lý đang soạn sẵn cho chị.',
      contentType: 'text',
      senderType: 'self',
      senderName: 'Nguyễn Tiến Lộc',
      sentAt: isoAgo(80),
      isDeleted: false,
      zaloMsgId: 'zmsg_402',
      zaloMsgIdNum: '400002',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      deliveredAt: isoAgo(79),
      seenAt: isoAgo(75),
      repliedByUserId: 'u-owner-1',
      repliedBy: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
      sentVia: 'user',
      reactions: [],
    },
  ],
  'conv-5': [
    {
      id: 'm-501',
      content: 'Cập nhật bảng hàng mới nhất lúc 14:00: Căn A2-18.06 đã lock thành công cho khách VIP của PKD1!',
      contentType: 'text',
      senderType: 'self',
      senderName: 'Nguyễn Tiến Lộc',
      sentAt: isoAgo(15),
      isDeleted: false,
      zaloMsgId: 'zmsg_501',
      zaloMsgIdNum: '500001',
      albumKey: null,
      albumIndex: null,
      albumTotal: null,
      reactions: [],
    },
  ],
};

export const DEMO_APPOINTMENTS = [
  {
    id: 'apt-1',
    contactId: 'ct-2',
    contact: { id: 'ct-2', fullName: 'Vũ Thị Bích Ngọc', phone: '0918223344', avatarUrl: null, zaloUid: 'zuid_kh_102' },
    appointmentDate: isoFuture(120),
    appointmentTime: '15:30',
    title: 'Đón chị Ngọc xem nhà mẫu Eaton Park & chốt căn góc',
    durationMin: 60,
    location: 'Sales Gallery Eaton Park, Đại lộ Mai Chí Thọ, TP. Thủ Đức',
    type: 'meeting',
    status: 'scheduled',
    notes: 'Chuẩn bị bảng tính dòng tiền cho thuê + chính sách thanh toán giãn 3 năm.',
    createdAt: isoAgo(600),
    source: 'zalo' as const,
    externalRef: 'zapt_01',
    zaloMessageId: 'm-203',
    emoji: '📅',
    conversationId: 'conv-2',
    statusChangedAt: null,
    statusChangedBy: null,
    assignedUserId: 'u-sale-1',
    assignedUser: { id: 'u-sale-1', fullName: 'Trần Minh Anh' },
    assignedToId: 'u-sale-1',
    assignedTo: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' },
  },
  {
    id: 'apt-2',
    contactId: 'ct-1',
    contact: { id: 'ct-1', fullName: 'Đặng Quốc Khánh', phone: '0903888999', avatarUrl: null, zaloUid: 'zuid_kh_101' },
    appointmentDate: isoFuture(210),
    appointmentTime: '17:00',
    title: 'Tư vấn 1-1 phương án dòng tiền Shophouse The Global City',
    durationMin: 45,
    location: 'Khu nhạc nước The Global City, Đỗ Xuân Hợp, TP. Thủ Đức',
    type: 'meeting',
    status: 'scheduled',
    notes: 'Mang theo hồ sơ pháp lý và mặt bằng chi tiết khu SOHO.',
    createdAt: isoAgo(480),
    source: 'manual' as const,
    externalRef: null,
    zaloMessageId: null,
    emoji: '🤝',
    conversationId: 'conv-1',
    statusChangedAt: null,
    statusChangedBy: null,
    assignedUserId: 'u-owner-1',
    assignedUser: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc' },
    assignedToId: 'u-owner-1',
    assignedTo: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
  },
  {
    id: 'apt-3',
    contactId: 'ct-3',
    contact: { id: 'ct-3', fullName: 'Trịnh Đình Quang', phone: '0977556677', avatarUrl: null, zaloUid: 'zuid_kh_103' },
    appointmentDate: isoFuture(1440),
    appointmentTime: '09:30',
    title: 'Gọi tư vấn hồ sơ thẩm định vay Vietcombank 70%',
    durationMin: 30,
    location: 'Gọi điện qua Zalo',
    type: 'call',
    status: 'scheduled',
    notes: 'Gửi trước danh mục hồ sơ chứng minh thu nhập.',
    createdAt: isoAgo(300),
    source: 'manual' as const,
    externalRef: null,
    zaloMessageId: null,
    emoji: '📞',
    conversationId: 'conv-3',
    statusChangedAt: null,
    statusChangedBy: null,
    assignedUserId: 'u-sale-2',
    assignedUser: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam' },
    assignedToId: 'u-sale-2',
    assignedTo: { id: 'u-sale-2', fullName: 'Lê Hoàng Nam', email: 'hoangnam@hsholding.vn' },
  },
];

export const DEMO_CUSTOMER_LISTS = [
  {
    id: 'cl-1',
    name: 'Tệp Khách Hàng VIP Đầu Tư Đông Sài Gòn Q2/2026',
    iconEmoji: '💎',
    sourceType: 'excel',
    status: 'done' as const,
    archivedAt: null,
    startedAt: isoAgo(2880),
    endedAt: isoAgo(2860),
    createdAt: isoAgo(2880),
    createdById: 'u-owner-1',
    createdBy: { id: 'u-owner-1', fullName: 'Nguyễn Tiến Lộc', email: 'admin@hsholding.vn' },
    totalEntries: 120,
    validEntries: 114,
    invalidEntries: 6,
    dupInListEntries: 3,
    dupCrossListEntries: 5,
    dupWithContactEntries: 18,
    hasZaloEntries: 98,
    noZaloEntries: 16,
    pendingLookupEntries: 0,
    platforms: ['manual'],
    leadNotifyEnabled: true,
  },
  {
    id: 'cl-2',
    name: 'Lead Facebook Ads — Chiến dịch Eaton Park Tháng 6',
    iconEmoji: '📣',
    sourceType: 'leadads',
    status: 'done' as const,
    archivedAt: null,
    startedAt: isoAgo(1440),
    endedAt: isoAgo(1400),
    createdAt: isoAgo(1440),
    createdById: 'u-sale-1',
    createdBy: { id: 'u-sale-1', fullName: 'Trần Minh Anh', email: 'minhanh@hsholding.vn' },
    totalEntries: 85,
    validEntries: 82,
    invalidEntries: 3,
    dupInListEntries: 1,
    dupCrossListEntries: 4,
    dupWithContactEntries: 12,
    hasZaloEntries: 74,
    noZaloEntries: 8,
    pendingLookupEntries: 0,
    platforms: ['fb-leadads'],
    fbLocked: true,
    leadNotifyEnabled: true,
  },
];

export const DEMO_DEPARTMENTS = [
  {
    id: 'dept-bds-1',
    name: 'Khối Kinh Doanh BĐS',
    parentId: null,
    path: '/dept-bds-1',
    depth: 0,
    displayOrder: 1,
    archivedAt: null,
    memberCount: 4,
    leaderUserId: 'u-owner-1',
    deputyUserId: 'u-sale-1',
    children: [
      {
        id: 'dept-bds-2',
        name: 'Phòng Kinh Doanh 1 — Đông Sài Gòn',
        parentId: 'dept-bds-1',
        path: '/dept-bds-1/dept-bds-2',
        depth: 1,
        displayOrder: 1,
        archivedAt: null,
        memberCount: 2,
        leaderUserId: 'u-sale-1',
        deputyUserId: null,
        children: [],
      },
      {
        id: 'dept-bds-3',
        name: 'Phòng Kinh Doanh 2 — Khu Nam',
        parentId: 'dept-bds-1',
        path: '/dept-bds-1/dept-bds-3',
        depth: 1,
        displayOrder: 2,
        archivedAt: null,
        memberCount: 1,
        leaderUserId: 'u-sale-3',
        deputyUserId: null,
        children: [],
      },
    ],
  },
];

export const DEMO_MEDIA_FOLDERS = [
  { id: 'mf-1', name: 'Mặt bằng & Bảng giá Eaton Park', kind: 'all', visibility: 'public' as const, ownerUserId: 'u-owner-1' },
  { id: 'mf-2', name: 'Pháp lý & Chính sách The Global City', kind: 'all', visibility: 'public' as const, ownerUserId: 'u-owner-1' },
  { id: 'mf-3', name: 'Tài liệu bán hàng Vinhomes Grand Park', kind: 'all', visibility: 'public' as const, ownerUserId: 'u-sale-1' },
];

export const DEMO_MEDIA_ITEMS = [
  {
    id: 'ma-1',
    kind: 'image' as const,
    name: 'Mat-bang-tang-18-Eaton-Park-3PN.png',
    visibility: 'public' as const,
    ownerUserId: 'u-owner-1',
    ownerName: 'Nguyễn Tiến Lộc',
    tagIds: ['eaton-park', 'mat-bang'],
    usageCount: 34,
    url: '/brand/zalocrm-logo.png',
    thumbnailUrl: '/brand/zalocrm-logo.png',
    sizeBytes: 1_450_000,
    createdAt: isoAgo(4320),
    favorited: true,
    source: 'upload' as const,
    width: 1920,
    height: 1080,
  },
  {
    id: 'ma-2',
    kind: 'file' as const,
    name: 'Bang-tinh-dong-tien-chiet-khau-8pct-TGC.pdf',
    visibility: 'public' as const,
    ownerUserId: 'u-owner-1',
    ownerName: 'Nguyễn Tiến Lộc',
    tagIds: ['the-global-city', 'bang-gia'],
    usageCount: 28,
    url: '/brand/zalocrm-logo.png',
    thumbnailUrl: null,
    sizeBytes: 2_840_000,
    createdAt: isoAgo(2880),
    favorited: true,
    source: 'upload' as const,
  },
  {
    id: 'ma-3',
    kind: 'file' as const,
    name: 'Chinh-sach-vay-Vietcombank-0pct-24-thang.xlsx',
    visibility: 'public' as const,
    ownerUserId: 'u-sale-1',
    ownerName: 'Trần Minh Anh',
    tagIds: ['vinhomes-grand-park', 'ngan-hang'],
    usageCount: 19,
    url: '/brand/zalocrm-logo.png',
    thumbnailUrl: null,
    sizeBytes: 860_000,
    createdAt: isoAgo(1440),
    favorited: false,
    source: 'upload' as const,
  },
];
